version: '3.8'

networks:
  auth_internal:
    external: true
  traefik:
    name: traefik
    external: true
  backend:

services:
  database:
    image: postgres
    hostname: database
    restart: unless-stopped
    volumes:
      - /mnt/ssd-1tb/docker/calcom-${SUBDOMAIN}.${DOMAIN}/db:/var/lib/postgresql/data/
    env_file:
      - stack.env
    networks:
      - backend
    labels:
      - traefik.enable = false

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_DIRECT_URL: ${DATABASE_URL}
      network: backend
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - backend
      - traefik
    env_file:
      - stack.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.calcom-${ID}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.calcom-${ID}.entrypoints=websecure
      - traefik.http.routers.calcom-${ID}.tls.certresolver=${DOMAIN}
      - traefik.http.services.calcom-${ID}.loadbalancer.server.port=3000
