# Use postgres/example user/password credentials
version: '3.8'

networks:
  auth_internal:
    external: true
  traefik:
    name: traefik
    external: true
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    volumes:
      - /mnt/ssd-1tb/docker/calcom/db:/var/lib/postgresql/data/
    env_file:
      - stack.env
    networks:
      - stack
    labels:
      - traefik.enable = false

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - stack
      - traefik
    env_file:
      - stack.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.calcom-patz.rule=Host(`cal.patz.app`)
      - traefik.http.routers.calcom-patz.entrypoints=websecure
      - traefik.http.routers.calcom-patz.tls.certresolver=patz.app
      - traefik.http.routers.calcom-patz.tls.domains[0].main=patz.app
      - traefik.http.routers.calcom-patz.tls.domains[0].sans=cal.patz.app
      - traefik.http.services.calcom-patz.loadbalancer.server.port=3000
